### ISSUE TITLE
Issue while generating tweet

### ISSUE THREAD

**Issue by XaheerINC** [marcolivierbouch/XReplyGPT#24]
Error while generating a reply for this tweet: Rate limit reached for gpt-3.5-turbo in organization org-gkOpuNhdF16oQJPCM1VAsca4 on requests per min (RPM): Limit 3, Used 3, Requested 1. Please try again in 20s. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing.

**Comment by marcolivierbouch** [comment]
Hi @XaheerINC this is an error from OpenAI you have to increase to a higher tier to have more RPM. It is not an issue from XReplyGPT
